### ISSUE TITLE
Problem with newest FlexCan library

### ISSUE THREAD

**Issue by ttlappalainen** [sarfata/NMEA2000_teensy#5]
Hi,

Have you tested with newest FlexCan library? I have Arduino 1.81 and Teensyduino 1.35. Board does not send anything to the bus. I replaced FlexCan from old setup and it works fine.

**Comment by AlbatrossVII** [comment]
I just discovered that myself. The old FlexCan library works great. The new library didn't receive anything, and sending would stop after a few messages.
BTW, thank you for a great library. I'm building an engine monitor for my ancient Volvo Penta. I might tackle a digital compass next :)

**Comment by ttlappalainen** [comment]
Any progress with this? I temporaly published old working code to  http://www.kave.fi/Apps/Arduino/Teensy/FlexCAN.zip

**Comment by ttlappalainen** [comment]
This has been fixed now. New NMEA2000_Teensy tries to quess version of FlexCAN library. I also forked and developed FlexCAN library under my repositories. I prefer that version, since it has better send/receive and full interrupt handling. You need the latest NMEA2000 library version.
